### ISSUE TITLE
JumpReLU SAE training on the roadmap?

### ISSUE THREAD

**Issue by ejmichaud** [saprmarks/dictionary_learning#19]
Just curious if anyone is thinking about implementing a training pipeline for JumpReLU SAEs! They have a couple of properties which are really desirable for something I'm working on.

**Comment by ejmichaud** [comment]
Ah whoops I see the `jump_trainer` branch now and that @canrager is working on it :)

**Comment by adamkarvonen** [comment]
This was just merged: https://github.com/saprmarks/dictionary_learning/pull/22

I'm not sure how well tested it is though. Let us know if you have any problems / how it works for you.

**Comment by adamkarvonen** [comment]
JumpReLU training is tested and working successfully.
