### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by kenza-bouzid** [saprmarks/dictionary_learning#24]
Hello, 

Would it be possible to add a license to this repo? Not having a license restricts users from using this code. Please refer to the [GitHub's licensing help page](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license). 

![image](https://github.com/user-attachments/assets/fb13e1f5-2979-4619-bffd-709f59fc2c51)

@saprmarks, @aaronmueller 

Many thanks.

**Comment by saprmarks** [comment]
Just did this—sorry it took so long to get to it.
