### ISSUE TITLE
One-dimensional Signal

### ISSUE THREAD

**Issue by zyy200196** [saprmarks/dictionary_learning#27]
Thank you for sharing! I wanna ask that can this idea be applied to one-dimensional signals?

**Comment by adamkarvonen** [comment]
It probably doesn't make sense? An L0 of 1 could perfectly reconstruct the input signal.

**Comment by zyy200196** [comment]
> It probably doesn't make sense? An L0 of 1 could perfectly reconstruct the input signal.

Thank you for your advice!
